name: Check Registration Fix

on:
  pull_request:
    branches: [ main ]

jobs:
  stage-tests:
    name: Playwright Stage Tests
    runs-on: ubuntu-latest
    steps:
      - run: echo "stage"

  prod-tests:
    name: Playwright Prod Tests
    runs-on: ubuntu-latest
    steps:
      - run: echo "prod"